export const ADD_BOX = 'ADD_BOX';
export const SET_ACTIVE_BOX = 'SET_ACTIVE_BOX';
export const ADD_RELATION = 'ADD_RELATION';
export const DELETE_RELATION = 'DELETE_RELATION';
export const UPDATE_BOX_POSITION = 'UPDATE_BOX_POSITION';
export const DEFAULT_TYPE = 'DEFAULT_TYPE';